/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'

export function Character({animation, ...props}) {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('/models/cc.glb')
    const {actions} = useAnimations(animations, group)
    useEffect(() => {


        actions[animation]?.reset().fadeIn(0.24).play()
        return () => actions?.[animation]?.fadeOut(0.24)
    }, [animation]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="fall_guys">

                    <skinnedMesh
                        name="hand-"
                        geometry={nodes['hand-'].geometry}
                        material={materials['Material.001']}
                        skeleton={nodes['hand-'].skeleton}
                    />
                    <skinnedMesh
                        name="leg"
                        geometry={nodes.leg.geometry}
                        material={materials['Material.001']}
                        skeleton={nodes.leg.skeleton}
                    />
                    <primitive object={nodes._rootJoint} />
                </group>
                <group
                    name="Antenna"
                    position={[0.347, 2.893, -0.292]}
                    rotation={[-0.103, 0, -0.347]}
                    scale={0.01}>
                    <mesh
                        name="Alien_Antenna001"
                        castShadow
                        receiveShadow
                        geometry={nodes.Alien_Antenna001.geometry}
                        material={materials['Material.002']}
                    />
                    <mesh
                        name="Alien_Antenna001_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Alien_Antenna001_1.geometry}
                        material={materials['Material.001']}
                    />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/cc.glb')