/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'

export function Coin({animation, ...props}) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/coin.glb')
    const {actions} = useAnimations(animations, group);
    useEffect(() => {
        actions[animation]?.reset().fadeIn(0.24).play();
        return () => actions?.[animation]?.fadeOut(0.24);
    }, [animation]);

    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.ImageToStlcom_d404ac4f940b0be3253aef0ad5ede22a.geometry}
                material={materials['Material.002']}
                position={[0, 2, 0]}
                rotation={[Math.PI / 2, 0, Math.PI / 2]}
            />
        </group>
    )
}

useGLTF.preload('/models/coin.glb')