/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Coffeek (https://sketchfab.com/coffe0wolf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/meat-fdcbd368e9454f559364a4ee794453a9
Title: Meat
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Meat(props) {
    const { nodes, materials } = useGLTF('/models/meat.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.first}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={materials.main}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_4.geometry}
                    material={materials.second}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/meat.glb')