/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Pudge(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/pudge.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="weaponvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="weaponvmdl_cweapon_model"
                        geometry={nodes.weaponvmdl_cweapon_model.geometry}
                        material={materials.pudge2_hook}
                        skeleton={nodes.weaponvmdl_cweapon_model.skeleton}
                    />
                    <primitive object={nodes.root} />
                </group>
                <group name="righthookvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="righthookvmdl_crighthook_model"
                        geometry={nodes.righthookvmdl_crighthook_model.geometry}
                        material={materials['pudge2_hook.001']}
                        skeleton={nodes.righthookvmdl_crighthook_model.skeleton}
                    />
                    <primitive object={nodes.weapon_rt_1_1} />
                    <primitive object={nodes.Knife_A_1} />
                    <primitive object={nodes.Knife_B_1} />
                    <primitive object={nodes.Knife_C_1} />
                    <primitive object={nodes.apron_tie_1_1} />
                    <primitive object={nodes.apron_R2C0_1} />
                    <primitive object={nodes.apron_R2C1_1} />
                </group>
                <group name="pudgevmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="pudgevmdl_cpudge_model"
                        geometry={nodes.pudgevmdl_cpudge_model.geometry}
                        material={materials.pudge2_body}
                        skeleton={nodes.pudgevmdl_cpudge_model.skeleton}
                        morphTargetDictionary={nodes.pudgevmdl_cpudge_model.morphTargetDictionary}
                        morphTargetInfluences={nodes.pudgevmdl_cpudge_model.morphTargetInfluences}
                    />
                    <primitive object={nodes.root_1} />
                </group>
                <group name="leftweaponvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="leftweaponvmdl_cleftweapon_model"
                        geometry={nodes.leftweaponvmdl_cleftweapon_model.geometry}
                        material={materials.pudge2_chopper}
                        skeleton={nodes.leftweaponvmdl_cleftweapon_model.skeleton}
                    />
                    <primitive object={nodes.weapon_lf_2_1} />
                    <primitive object={nodes.Knife_A_3} />
                    <primitive object={nodes.Knife_B_3} />
                    <primitive object={nodes.Knife_C_3} />
                    <primitive object={nodes.apron_tie_1_3} />
                    <primitive object={nodes.apron_R2C0_3} />
                    <primitive object={nodes.apron_R2C1_3} />
                </group>
                <group name="leftarmvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="leftarmvmdl_cleftarm_model"
                        geometry={nodes.leftarmvmdl_cleftarm_model.geometry}
                        material={materials.pudge2_armleft}
                        skeleton={nodes.leftarmvmdl_cleftarm_model.skeleton}
                    />
                    <primitive object={nodes.root_2} />
                </group>
                <group name="hairvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="hairvmdl_chair_model"
                        geometry={nodes.hairvmdl_chair_model.geometry}
                        material={materials.pudge2_hair}
                        skeleton={nodes.hairvmdl_chair_model.skeleton}
                    />
                    <primitive object={nodes.head_2} />
                    <primitive object={nodes.Knife_A_5} />
                    <primitive object={nodes.Knife_B_5} />
                    <primitive object={nodes.Knife_C_5} />
                    <primitive object={nodes.apron_tie_1_5} />
                    <primitive object={nodes.apron_R2C0_5} />
                    <primitive object={nodes.apron_R2C1_5} />
                </group>
                <group name="bracervmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="bracervmdl_cbracer_model"
                        geometry={nodes.bracervmdl_cbracer_model.geometry}
                        material={materials.pudge2_bracer}
                        skeleton={nodes.bracervmdl_cbracer_model.skeleton}
                    />
                    <primitive object={nodes.bicep_R_1} />
                    <primitive object={nodes.Knife_A_6} />
                    <primitive object={nodes.Knife_B_6} />
                    <primitive object={nodes.Knife_C_6} />
                    <primitive object={nodes.apron_tie_1_6} />
                    <primitive object={nodes.apron_R2C0_6} />
                    <primitive object={nodes.apron_R2C1_6} />
                </group>
                <group name="beltvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="beltvmdl_cbelt_model"
                        geometry={nodes.beltvmdl_cbelt_model.geometry}
                        material={materials.pudge2_waist}
                        skeleton={nodes.beltvmdl_cbelt_model.skeleton}
                    />
                    <primitive object={nodes.root_3} />
                </group>
                <group name="back_refitvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="back_refitvmdl_cpudge_back_lod0_refit"
                        geometry={nodes.back_refitvmdl_cpudge_back_lod0_refit.geometry}
                        material={materials.pudge2_apron}
                        skeleton={nodes.back_refitvmdl_cpudge_back_lod0_refit.skeleton}
                    />
                    <primitive object={nodes.root_4} />
                </group>
                <group name="backvmdl_c" rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.025}>
                    <skinnedMesh
                        name="backvmdl_cback_model"
                        geometry={nodes.backvmdl_cback_model.geometry}
                        material={materials['pudge2_apron.001']}
                        skeleton={nodes.backvmdl_cback_model.skeleton}
                    />
                    <primitive object={nodes.root_5} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/pudge.glb')