/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/pudge.gltf -o src/components/Pudge.jsx -r public -k 
*/

import React, {useEffect, useRef} from 'react'
import {useGLTF, useAnimations} from '@react-three/drei'

export function Pudge({animation, ...props}) {
    const group = useRef()
    const {nodes, materials, animations} = useGLTF('/models/pudge.gltf')
    const {actions} = useAnimations(animations, group)


    useEffect(() => {
        actions[animation]?.reset().fadeIn(0.24).play()
        return () => actions?.[animation]?.fadeOut(0.24)
    }, [animation]);


    return (
        <group ref={group} {...props} dispose={null} scale={0.3}>
            <group name="Scene">
                <group name="fall_guys">


                    <group name="ultimate">
                        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                            <primitive object={nodes.root}/>
                            <skinnedMesh name="pudge_arms" geometry={nodes.pudge_arms.geometry}
                                         material={materials.blinn4} skeleton={nodes.pudge_arms.skeleton}/>
                            <skinnedMesh name="pudge_back" geometry={nodes.pudge_back.geometry}
                                         material={materials.blinn1} skeleton={nodes.pudge_back.skeleton}/>
                            <skinnedMesh name="pudge_back_hoops" geometry={nodes.pudge_back_hoops.geometry}
                                         material={materials.blinn1} skeleton={nodes.pudge_back_hoops.skeleton}/>
                            <skinnedMesh name="pudge_base" geometry={nodes.pudge_base.geometry}
                                         material={materials.blinn3} skeleton={nodes.pudge_base.skeleton}/>
                            <skinnedMesh name="pudge_base_legs" geometry={nodes.pudge_base_legs.geometry}
                                         material={materials.blinn3} skeleton={nodes.pudge_base_legs.skeleton}/>
                            <skinnedMesh name="pudge_belt" geometry={nodes.pudge_belt.geometry}
                                         material={materials.blinn8} skeleton={nodes.pudge_belt.skeleton}/>
                            <skinnedMesh name="pudge_belt_knives" geometry={nodes.pudge_belt_knives.geometry}
                                         material={materials.blinn8} skeleton={nodes.pudge_belt_knives.skeleton}/>
                            <skinnedMesh name="pudge_head" geometry={nodes.pudge_head.geometry}
                                         material={materials.blinn6} skeleton={nodes.pudge_head.skeleton}/>
                            <skinnedMesh name="pudge_offhand_weapon" geometry={nodes.pudge_offhand_weapon.geometry}
                                         material={materials.blinn5} skeleton={nodes.pudge_offhand_weapon.skeleton}/>
                            <skinnedMesh name="pudge_shoulder" geometry={nodes.pudge_shoulder.geometry}
                                         material={materials.blinn2} skeleton={nodes.pudge_shoulder.skeleton}/>
                            <skinnedMesh name="pudge_weapon" geometry={nodes.pudge_weapon.geometry}
                                         material={materials.blinn7} skeleton={nodes.pudge_weapon.skeleton}/>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/pudge.gltf')
